# This is a basic workflow to help you get started with Actions

name: Get OpenWrt Config

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the openwrt-21.02 branch
  push:
    branches: [ openwrt-21.02 ]
  # pull_request:
  #  branches: [ openwrt-21.02 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buildJob"
  buildJob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # 安装依赖
      - name: Installation depends
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
      # sudo apt-get -y install libpam liblzma libnetsnmp
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 生成默认的config文件
      - name: Generate config file
        run: |
          make defconfig
          
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt.config
          path: ./bin
          
          
